services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config:/config
    restart: unless-stopped
    stop_grace_period: 60s
    privileged: true
    environment:
      TZ: Europe/London
    ports:
      - '8123:8123'